### ISSUE TITLE
Support for different aspect ratios

### ISSUE THREAD

**Issue by DigitalE4rth** [DigitalE4rth/AuroraDialogEnhancer#36]

**Comment by DigitalE4rth** [comment]
Actually, I have an idea how to make it done quickly. I'll test it later 🤔

**Comment by boelzzzka** [comment]
Hi.. its me who commented on youtube, I think I found the problem, when I start the game 1920x822 the cursor always stay at the bottom even when I change it to 1600x900 and pressed f5, but if I change to 1600x900 and restart the game it work perfectly.
So maybe it should 16:9 or 16:10 from the start. idk haha

**Comment by DigitalE4rth** [comment]
> Hi.. its me who commented on youtube, I think I found the problem, when I start the game 1920x822 the cursor always stay at the bottom even when I change it to 1600x900 and pressed f5, but if I change to 1600x900 and restart the game it work perfectly. So maybe it should 16:9 or 16:10 from the start. idk haha

Yeah, I just tested everything, there's no quick fix. I need to run new dependency calculations for the new aspect ratios. On the plus side, these new calculations will give me a difference from which I can derive data dependencies for other aspect ratios. I apologize, but this issue will not be a top priority for now. It's not that hard, but it's a big task. But I think by the end of this year I'll fix this issue. (´。＿。｀)

**Comment by DigitalE4rth** [comment]
I've gathered all the necessary data for the 21:9 aspect ratio. It was a little easier than I thought. If all goes well, it should be up and running by the end of next week 🤙🤙

**Comment by DigitalE4rth** [comment]
Supported resolutions/aspect ratios
|Tested|Width|Height|Ratio %|Ratio|
|---|---|---|---|---|
|✅|1280|1024|1.25|5:4|
|====|====|====|====|====|
|✅|800|600|1.333|4:3|
|✅|1024|768|1.333|4:3|
|✅|1152|864|1.333|4:3|
|✅|1280|960|1.333|4:3|
|✅|1600|1200|1.333|4:3|
|✅|1920|1440|1.333|4:3|
|====|====|====|====|====|
|✅|1920|1280|1.5|3:2|
|====|====|====|====|====|
|✅|1280|800|1.6|16:10|
|✅|1680|1050|1.6|16:10|
|✅|1920|1200|1.6|16:10|
|====|====|====|====|====|
|✅|1280|768|1.66|5:3|
|====|====|====|====|====|
|✅|1360|768|1.770|16:9|
|✅|1280|720|1.777|16:9|
|✅|1920|1080|1.777|16:9|
|✅|2560|1440|1.777|16:9|
|✅|1366|768|1.778|16:9|
|====|====|====|====|====|
|✅|1920|833|2.304|21:9|
|====|====|====|====|====|
|✅|3840|1648|2.33|21:9|
|✅|1280|549|2.331|21:9|
|✅|1920|823|2.332|21:9|
|✅|3840|1646|2.332|21:9|
|✅|3840|1644|2.335|21:9|
|====|====|====|====|====|
|✅|3840|1632|2.352|21:9|
|====|====|====|====|====|
|✅|2560|1080|2.370|21:9|
|✅|3840|1620|2.370|21:9|
|====|====|====|====|====|
|✅|3840|1608|2.380|21:9|
|====|====|====|====|====|
|✅|3840|1440|2.388|21.5:9|
|====|====|====|====|====|
|✅|3840|1600|2.4|21:9|
|====|====|====|====|====|
|✅|3840|1200|3.2|32:10|
|====|====|====|====|====|
|✅|3840|1080|3.55|32:9|
