### ISSUE TITLE
Add ability to use "W" and "S" to move the selection up and down.

### ISSUE THREAD

**Issue by timmychan97** [DigitalE4rth/AuroraDialogEnhancer#67]
Hi, this is really nice tool to use when playing Genshin Impact! Great job!

**Comment by DigitalE4rth** [comment]
thx!)

Uggh. You can set absolutely any buttons for all the actions in the “Key bindings” section. Or am I missing something?

**Comment by timmychan97** [comment]
Oh, I found it. Nice! 😄
