### ISSUE TITLE
I would like to submit a Chinese translation for this project. What should I do?

### ISSUE THREAD

**Issue by StarChenPy** [DigitalE4rth/AuroraDialogEnhancer#68]
How do I create the lang file (if any)?

**Comment by DigitalE4rth** [comment]
Hi, this was the least prioritized task. I kept thinking about taking the translation out of the program into separate xml file packages, but never got around to it. So far everything is embedded in the application [Resources.resx](https://github.com/DigitalE4rth/AuroraDialogEnhancer/blob/main/AuroraDialogEnhancer/Properties/Localization/Resources.resx).

I'm working on a big update right now, and I think within a couple weeks I'll get to that task as well. I would be very grateful for the translation. You can start translating now, and then just drop me the file later (what a mess...). And as soon as I get to it and rework everything, I'll add your translation to the ADE and list you in the credits.

Thank you 🙏

**Comment by StarChenPy** [comment]
@DigitalE4rth I have finished the translation and placed the file here
[Resources.zip](https://github.com/user-attachments/files/16062761/Resources.zip)

**Comment by DigitalE4rth** [comment]
Thank you 🥰🙏
You've helped a lot
